### ISSUE TITLE
`file.hidden_by_limit` doesn't work correctly

### ISSUE THREAD

**Issue by cocasema** [sgratzl/slack_cleaner2#101]
Probably due to API changes some time ago

**To Reproduce**
``` python
s = SlackCleaner(...)

for file in s.files(before=before):
  if file.hidden_by_limit:
    continue
  print(file.json)
  print(file.user)
```

**Expected behavior**
Hidden files are skipped

**Screenshots**
```
{'id': 'XXXXX', 'mode': 'hidden_by_limit', 'channels': [], 'groups': [], 'ims': ['YYYYYYYY']}
Traceback (most recent call last):
  File "my-slack-cleaner.py", line 35, in <module>
    print(file.user)
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "my-slack-cleaner/src/slack-cleaner2/slack_cleaner2/model.py", line 705, in user
    return self._slack.users.resolve_user(self.json["user"])
KeyError: 'user'
```

**Context**

- Version: 2.3.6
- Python Version:  3.10

**Additional context**
https://github.com/sgratzl/slack_cleaner2/blob/d8e6a82d9fc1f00c2ae5952cf97b6b82ae889412/slack_cleaner2/model.py#L681

``` python
class SlackFile:
    ...
    def __init__(self, entry: JSONDict, slack: "SlackCleaner"):
        ...
        self.id = entry["id"]
        self.hidden_by_limit = "hidden_by_limit" in entry ### something like `entry.get("mode", "") == "hidden_by_limit"`
        self.name = entry.get("name", "Unknown")
        ...
 ```

**Comment by sgratzl** [comment]
fixed in v3.2.7
