### ISSUE TITLE
Docker image crashing

### ISSUE THREAD

**Issue by azfarhashmi** [sgratzl/slack_cleaner2#41]
I tried the docker way with below config but its failing with errors.

script.py:

`from slack_cleaner2 import *
s = SlackCleaner('xoxp-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxx')
s.users`

Resulted in:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/__init__.py", line 5, in <module>
    from .predicates import and_, or_, is_not_pinned, is_bot, match, is_name, match_text, match_user, is_member, by_user, by_users
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/predicates.py", line 9, in <module>
    from .model import SlackUser
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/model.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by sgratzl** [comment]
thx due to the latest changes in the underlying library, the requests dependency got missing, should be fixed in v3.0.1
