### ISSUE TITLE
Problem with removing #general channel messages: cant_delete_message prompt obtained.

### ISSUE THREAD

**Issue by foxtrot-charlie** [sgratzl/slack_cleaner2#49]
When I run clean_general.py with the code indicated [here](https://github.com/sgratzl/slack-cleaner/issues/79) (shown below too):

```
from slack_cleaner2 import SlackCleaner
s = SlackCleaner("xoxb-xxxxxxxxxxxx-xxxxxxxxxxxxx-blablablablabla", sleep_for=1)
for msg in s.c.general.msgs(with_replies=True):
  msg.delete()
```

I get an error response like:
`xcannot delete entry: general:1614xxxxxx.0001 (username (Uxxxxxxxxxx) userabbreviation): <@Uxxxxxxxxxx> has j: cant_delete_message`

For all messages.

**To Reproduce**

1. Create an app with all possibly required Bot Scopes (triple checked), install app in the Workspace.
2. Add the Slack Cleaner 2 bot to #general channel, where it has to take action.
2. Create a .py script with SublimeText containing the code indicated above, with the right 'xoxb-...' Bot User OAuth Token.
2. Execute it with macOS 10.15.7 (Catalina) Terminal with 'python clean_general.py"
3. Obtain prompts every second starting with 'xcannot delete entry: [...]'

**Expected behavior**

I would expect it to erase the messages.

**Screenshots**

Doesn't add additional information.

**Context**

- Version: 
- Python Version: 3.8

**Additional context**

Excerpt of the return message after quitting job in Terminal:
```
Traceback (most recent call last):
  File "clean_general.py", line 4, in <module>
    msg.delete()
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_cleaner2/model.py", line 436, in delete
    self._delete_rated(as_user)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_cleaner2/model.py", line 408, in _delete_rated
    return self._slack.client.chat_delete(channel=self._channel.id,
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/client.py", line 1071, in chat_delete
    return self.api_call("chat.delete", json=kwargs)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 134, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 170, in _sync_send
    return self._urllib_api_call(
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 281, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/site-packages/slack_sdk/web/base_client.py", line 403, in _perform_urllib_http_request
    resp = urlopen(  # skipcq: BAN-B310
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/myuser/opt/anaconda3/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/Users/myuser/opt/anaconda3/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/Users/myuser/opt/anaconda3/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by foxtrot-charlie** [comment]
Problem solved, my bad: Bot Scopes were set, but **User Scopes** should have been set instead. Changing it solved it immediately. 

**Solution was found** by interrupting the process immediately after a ```cannot delete entry:``` prompt, which provided valuable feedback in the "Traceback" list.
