### ISSUE TITLE
slack-cleaner2 command not working

### ISSUE THREAD

**Issue by phbissiwu** [sgratzl/slack_cleaner2#75]
When I run slack-cleaner2 I get this error

Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/slack-cleaner2", line 33, in <module>
    sys.exit(load_entry_point('slack-cleaner2', 'console_scripts', 'slack-cleaner2')())
  File "/home/ec2-user/.local/bin/slack-cleaner2", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/running-script/src/slack-cleaner2/slack_cleaner2/__init__.py", line 5, in <module>
    from .predicates import and_, or_, is_not_pinned, is_bot, match, is_name, match_text, match_user, is_member, by_user, by_users
  File "/home/ec2-user/running-script/src/slack-cleaner2/slack_cleaner2/predicates.py", line 9, in <module>
    from .model import SlackUser
  File "/home/ec2-user/running-script/src/slack-cleaner2/slack_cleaner2/model.py", line 12, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/usr/lib64/python3.7/functools.py)

The command is broken

**To Reproduce**

1. run slack-cleaner2

**Expected behavior**

**Screenshots**

**Context**

- Version:
- Python Version: 

**Additional context**

**Comment by sgratzl** [comment]
please try it out with a newer python version than 3.7, e.g. 3.9
