### ISSUE TITLE
`KeyError: 'mode'`

### ISSUE THREAD

**Issue by kousu** [sgratzl/slack_cleaner2#77]
When I try to clean up my messages, my script hits a bad message and crashes.

This was working a few weeks ago. Is it possible Slack has changed their API?

I'm not sure what the bad message is because the crash happens internally, before it's returned to me.

**To Reproduce**

Save this script:

<details><summary>tidy-slack.py</summary>

```python
#!/usr/bin/env python3

import sys, os
import datetime
from slack_cleaner2 import SlackCleaner
from tqdm import tqdm

from pprint import pprint

# one month ago, in a format slack-cleaner wants
AGO = (datetime.datetime.now().date() - datetime.timedelta(28)).strftime("%Y%m%d")

s = SlackCleaner(os.getenv("SLACK_TOKEN",""), sleep_for=0.1)

for i, m in enumerate(s.msgs(before=AGO, with_replies=True)): # with_replies means: find messages inside subthreads too
    print(i)
    if m.user == s.myself and not m.pinned_to:
        # beware: m.user can be None (in case of deleted users who left messages behind); so m.user.name can fail
        # but the if: guards against that case.
        print('Removing', f'{datetime.datetime.fromtimestamp(m.ts).ctime()}: {m.user.name} in #{m.channel}: {m.text}')
        m.delete(files=True, replies=True)
```

</details>

Get a Slack token.

Run the script like:

```
sh -c 'SLACK_TOKEN=xoxp-XXXXXX-XXXXXXXXxx-XXXXXXXXXXXXXXXx-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx time ./tidy-slack.py'
```

**Expected behavior**

Tidy up all my old messages please :)

**Screenshots**

```
$ sh -c 'SLACK_TOKEN=xoxp-XXXXXX-XXXXXXXXxx-XXXXXXXXXXXXXXXx-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx time ./tidy-slack.py'
0
1
2
3
[...]
43816
43817
43818
43819
43806it [05:52, 82.60it/s] Removing Tue Dec  1 15:23:29 2020: USER in #CHANNELNAME: <@UUUUUUUUU> has joined the channel
xcannot delete entry: CHANNELNAME:1606854209.0006 (USER (UUUUUUUUU) FirstName LastName): <@UUUUUUUUU> has joi: cant_delete_message
43820
43821
Traceback (most recent call last):
  File "/home/user/tidy-slack.py", line 38, in <module>
    for i, m in enumerate(s.msgs(before=AGO, with_replies=True)): # with_replies means: find messages inside subthreads too
  File "/usr/lib/python3/dist-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
  File "/home/user/.local/lib/python3.10/site-packages/slack_cleaner2/model.py", line 1416, in msgs
    for msg in channel.msgs(after=after, before=before, with_replies=with_replies):
  File "/home/user/.local/lib/python3.10/site-packages/slack_cleaner2/model.py", line 249, in msgs
    s_msg = SlackMessage(msg, self, self._slack)
  File "/home/user/.local/lib/python3.10/site-packages/slack_cleaner2/model.py", line 416, in __init__
    self.files = [SlackFile(f, slack) for f in entry.get("files", []) if f["mode"] != "tombstone"]
  File "/home/user/.local/lib/python3.10/site-packages/slack_cleaner2/model.py", line 416, in <listcomp>
    self.files = [SlackFile(f, slack) for f in entry.get("files", []) if f["mode"] != "tombstone"]
KeyError: 'mode'
Command exited with non-zero status 1
33.88user 2.92system 5:52.51elapsed 10%CPU (0avgtext+0avgdata 41168maxresident)k
136inputs+0outputs (0major+12325minor)pagefaults 0swaps
```

**Context**

- Version:

```
$ pip list | grep slack-cleaner2
slack-cleaner2                             3.1.1
```

- Python Version: 

```
$ python --version
Python 3.10.4
```

**Comment by kousu** [comment]
I patched my local slack-cleaner2 so I could see what the bad message is (which I've censored partially):

```
{'blocks': [{'block_id': 'zfbig',
             'elements': [{'elements': [{'text': 'Explication de '
                                                 'l’architecture de GraphCore',
                                         'type': 'text'}],
                           'type': 'rich_text_section'}],
             'type': 'rich_text'}],
 'display_as_bot': False,
 'files': [{'created': 0,
            'file_access': 'external_access_denied',
            'id': 'F01XXXXXXXXXX',
            'timestamp': 0,
            'user': 'UUUUUUUUUU'}],
 'source_team': 'TP999999999',
 'team': 'T09999999',
 'text': 'Explication de l’architecture de GraphCore',
 'ts': '1602261291.001900',
 'type': 'message',
 'upload': False,
 'user': 'UUUUUUUUU',
 'user_profile': {'avatar_hash': '5555555555',
                  'display_name': '',
                  'first_name': 'George',
                  'image_72': 'https://avatars.slack-edge.com/2020-20-20/7777777777777_ababababababababab_72.jpg',
                  'is_restricted': False,
                  'is_ultra_restricted': False,
                  'name': 'george.vanier',
                  'real_name': 'George Vanier',
                  'team': 'TP999999999'},
 'user_team': 'TP999999999'}
```

It looks like this is a message in one of those pseudo-federated channels that Slack added a couple years ago, and I don't have access rights to see the attached file.

**Comment by kousu** [comment]
I patched the crashing line to read

```python
        self.files = [SlackFile(f, slack) for f in entry.get("files", []) if f.get("mode", "tombstone") != "tombstone"]
```

and now my script runs to completion. But I think this is probably not the ideal solution.

**Comment by kousu** [comment]
Thanks for the quick turnaround @sgratzl !!
