### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by sdunnedeloitte** [sgratzl/slack_cleaner2#9]
Hi, when running the following;

```python
import slack_cleaner2
from slack_cleaner2 import *

slack_token = 'xoxp-3xxxx'
s = SlackCleaner(slack_token)
```

i get an error of;

bash-3.2$ python slacktest.py 
```
Traceback (most recent call last):
  File "slacktest.py", line 6, in <module>
    s = SlackCleaner(slack_token, )
  File "/Users/sdunne/.local/share/virtualenvs/deloitte-slackbot-Aa84dEpA/lib/python3.7/site-packages/slack_cleaner2/model.py", line 720, in __init__
    self.ims = [SlackDirectMessage(m, self.user[m["user"]], slack.im, self) for m in _safe_list(slack.im.list(), "ims")]
  File "/Users/sdunne/.local/share/virtualenvs/deloitte-slackbot-Aa84dEpA/lib/python3.7/site-packages/slack_cleaner2/model.py", line 720, in <listcomp>
    self.ims = [SlackDirectMessage(m, self.user[m["user"]], slack.im, self) for m in _safe_list(slack.im.list(), "ims")]
KeyError: 'U0J5HN0CF'
```

This has previously been working fine and has suddenly stopped. Debug shows that it is collecting users, channels, groups, mpim and then failing...

Any idea on what could cause this?

Thanks!

**Comment by sgratzl** [comment]
seems like it cannot a specific user. currently working on patch to avoid this error
